server:
  port: 8000

spring:
  application:
    name: eurka-server  #服务名称
  datasource:
    name: test  #数据库名称
    url: jdbc:mysql://localhost:3306/springboot_v1?serverTimezone=UTC #url
    username: root  #账户
    password: 123456  #密码
    driver-class-name: com.mysql.cj.jdbc.Driver  #数据库驱动

eureka:
  instance:
    hostname: localhost # 设置主机名
  client:
    registerWithEureka: false # 是否向 Eureka 注册服务。该应用为服务注册中心，不需要自注册，设置为 false
    fetchRegistry: false # 是否检索服务。该应用为服务注册中心，职责为注册和发现服务，无需检索服务，设置为 false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/ # 注册中心url
